
DROP TABLE IF EXISTS Messages;
DROP TABLE IF EXISTS Chatrooms;
DROP TABLE IF EXISTS Users;

CREATE TABLE IF NOT EXISTS Users(
id SERIAL PRIMARY KEY,
login VARCHAR(255),
password VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Chatrooms(
id SERIAL PRIMARY KEY,
name VARCHAR(255),
owner_id INTEGER,
FOREIGN KEY (owner_id) REFERENCES Users(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Messages(
id SERIAL PRIMARY KEY,
author_id INTEGER,
room_id INTEGER,
text VARCHAR(255),
Date TIMESTAMP,
FOREIGN KEY (room_id) REFERENCES Chatrooms(id) ON UPDATE CASCADE ON DELETE SET NULL,
FOREIGN KEY (author_id) REFERENCES Users(id) ON UPDATE CASCADE ON DELETE SET NULL
);